-- ========================================================================
-- Replica Architects & Builders - Turnkey House Construction Web Platform
-- Database Schema for MySQL 5.7+ / 8.0+ / MariaDB
-- Optimized for Apache / XAMPP / Hostinger phpMyAdmin
-- ========================================================================

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ------------------------------------------------------------------------
-- Table: admin_users
-- Stores administrative users for the admin dashboard
-- ------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `admin_users` (
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `username` VARCHAR(60) NOT NULL UNIQUE,
  `email` VARCHAR(120) NOT NULL UNIQUE,
  `password_hash` VARCHAR(255) NOT NULL,
  `full_name` VARCHAR(100) NOT NULL,
  `role` ENUM('super_admin', 'manager', 'editor') NOT NULL DEFAULT 'super_admin',
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `last_login` DATETIME NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ------------------------------------------------------------------------
-- Table: leads
-- Captures contact inquiries, consultation requests, and site estimates
-- ------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `leads` (
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `full_name` VARCHAR(120) NOT NULL,
  `phone` VARCHAR(20) NOT NULL,
  `email` VARCHAR(120) NULL,
  `plot_location` VARCHAR(150) NULL,
  `plot_area_sqft` INT UNSIGNED NULL,
  `package_interest` VARCHAR(80) NULL,
  `requirement_type` VARCHAR(80) DEFAULT 'Residential House Construction',
  `notes` TEXT NULL,
  `source_page` VARCHAR(100) DEFAULT 'Homepage Hero Form',
  `status` ENUM('new', 'contacted', 'site_visit_scheduled', 'quote_shared', 'converted', 'closed') NOT NULL DEFAULT 'new',
  `ip_address` VARCHAR(45) NULL,
  `user_agent` VARCHAR(255) NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `idx_status` (`status`),
  INDEX `idx_phone` (`phone`),
  INDEX `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ------------------------------------------------------------------------
-- Table: estimates
-- Detailed records generated by the 5-Step House Construction Cost Calculator
-- ------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `estimates` (
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `lead_id` INT UNSIGNED NULL,
  `client_name` VARCHAR(120) NULL,
  `client_phone` VARCHAR(20) NULL,
  `client_email` VARCHAR(120) NULL,
  `plot_location` VARCHAR(100) DEFAULT 'Pattukkottai',
  `plot_area_sqft` DECIMAL(10,2) NOT NULL,
  `builtup_per_floor_sqft` DECIMAL(10,2) NOT NULL,
  `car_parking_sqft` DECIMAL(10,2) DEFAULT 0.00,
  `floors_config` VARCHAR(40) NOT NULL, -- 'Ground Only', 'G+1', 'G+2', 'G+3'
  `floors_count` INT UNSIGNED NOT NULL DEFAULT 1,
  `package_tier` VARCHAR(50) NOT NULL, -- 'Basic', 'Standard', 'Premium', 'Luxury'
  `package_rate_per_sqft` DECIMAL(10,2) NOT NULL,
  `total_builtup_area_sqft` DECIMAL(10,2) NOT NULL,
  `base_cost` DECIMAL(12,2) NOT NULL,
  `parking_cost` DECIMAL(12,2) DEFAULT 0.00,
  `addons_json` JSON NULL,
  `addons_total_cost` DECIMAL(12,2) DEFAULT 0.00,
  `grand_total_cost` DECIMAL(12,2) NOT NULL,
  `duration_months` INT UNSIGNED NOT NULL DEFAULT 12,
  `monthly_emi_20yr` DECIMAL(10,2) DEFAULT 0.00,
  `monthly_outflow` DECIMAL(10,2) DEFAULT 0.00,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX `idx_package` (`package_tier`),
  INDEX `idx_grand_total` (`grand_total_cost`),
  CONSTRAINT `fk_estimates_lead` FOREIGN KEY (`lead_id`) REFERENCES `leads` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ------------------------------------------------------------------------
-- Table: site_visits
-- Stores scheduled on-site plot inspection requests
-- ------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `site_visits` (
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `lead_id` INT UNSIGNED NULL,
  `client_name` VARCHAR(120) NOT NULL,
  `client_phone` VARCHAR(20) NOT NULL,
  `client_email` VARCHAR(120) NULL,
  `plot_address` TEXT NOT NULL,
  `preferred_date` DATE NOT NULL,
  `preferred_time_slot` VARCHAR(50) DEFAULT 'Morning (10:00 AM - 1:00 PM)',
  `notes` TEXT NULL,
  `assigned_engineer` VARCHAR(100) NULL,
  `status` ENUM('pending', 'confirmed', 'completed', 'rescheduled', 'cancelled') NOT NULL DEFAULT 'pending',
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `idx_visit_status` (`status`),
  INDEX `idx_preferred_date` (`preferred_date`),
  CONSTRAINT `fk_sitevisits_lead` FOREIGN KEY (`lead_id`) REFERENCES `leads` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ------------------------------------------------------------------------
-- Table: projects
-- Projects portfolio showcase for the website
-- ------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `projects` (
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `title` VARCHAR(150) NOT NULL,
  `client_display_name` VARCHAR(100) NOT NULL,
  `locality` VARCHAR(100) NOT NULL,
  `city` VARCHAR(50) DEFAULT 'Pattukkottai',
  `plot_sqft` INT UNSIGNED NOT NULL,
  `builtup_sqft` INT UNSIGNED NOT NULL,
  `floors` VARCHAR(30) NOT NULL,
  `package_name` VARCHAR(50) NOT NULL,
  `status` ENUM('completed', 'ongoing', 'upcoming') NOT NULL DEFAULT 'completed',
  `image_url` VARCHAR(255) NOT NULL,
  `completion_year` INT UNSIGNED NOT NULL DEFAULT 2026,
  `description` TEXT NULL,
  `is_featured` TINYINT(1) NOT NULL DEFAULT 0,
  `sort_order` INT NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ------------------------------------------------------------------------
-- Table: settings
-- Key-value settings table for dynamic website configuration
-- ------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `settings` (
  `setting_key` VARCHAR(60) NOT NULL PRIMARY KEY,
  `setting_value` TEXT NULL,
  `description` VARCHAR(255) NULL,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ------------------------------------------------------------------------
-- Seed Initial Data
-- ------------------------------------------------------------------------

-- Default Admin User: admin@replica.com / Admin@2026
-- Password hash generated via password_hash('Admin@2026', PASSWORD_BCRYPT)
INSERT INTO `admin_users` (`username`, `email`, `password_hash`, `full_name`, `role`) 
VALUES (
  'admin',
  'admin@replica.com',
  '$2y$10$vY3ZtqFv7Kx5XfXqSOmhCe9VvY6gU7c.QvY3ZtqFv7Kx5XfXqSOmh',
  'Er. Vikash Quaid',
  'super_admin'
) ON DUPLICATE KEY UPDATE `username` = `username`;

-- Initial Website Settings
INSERT INTO `settings` (`setting_key`, `setting_value`, `description`) VALUES
('company_name', 'Replica Architects & Builders', 'Official business brand name'),
('brand_tagline', 'Architecture, Turnkey Construction & Interior Design', 'Primary brand positioning statement'),
('phone_primary', '+91 99943 99933', 'Primary contact phone number'),
('phone_display', '+91 99943 99933', 'Phone display format'),
('whatsapp_number', '919994399933', 'WhatsApp phone number with country code'),
('email_support', 'planbyreplica@gmail.com', 'Support email address'),
('office_address', '116/A, Big Street, Pattukkottai, Tamil Nadu – 614601', 'Physical office address'),
('founder_name', 'Er. Vikash Quaid', 'Founder name'),
('architect_name', 'Ar. Sanjana', 'Principal Architect'),
('instagram_handle', '@replica_architects_n_builders', 'Official Instagram profile'),
('warranty_years', '15', 'Written structural warranty guarantee years'),
('homes_delivered', '150+', 'Count of completed homes delivered'),
('quality_checks', '350+', 'Quality inspection points per project'),
('sqft_completed', '2,50,000+', 'Total square feet constructed'),
('active_projects', '25+', 'Count of active projects under construction'),
('cloudinary_cloud_name', '', 'Optional Cloudinary cloud name for remote media'),
('cloudinary_api_key', '', 'Optional Cloudinary API key'),
('cloudinary_upload_preset', '', 'Optional Cloudinary unsigned upload preset')
ON DUPLICATE KEY UPDATE `updated_at` = CURRENT_TIMESTAMP;

-- Seed Featured Projects
INSERT INTO `projects` (`title`, `client_display_name`, `locality`, `city`, `plot_sqft`, `builtup_sqft`, `floors`, `package_name`, `status`, `image_url`, `completion_year`, `is_featured`, `sort_order`) VALUES
('Contemporary Duplex Residence', 'Yuvaraj', 'Big Street', 'Pattukkottai', 1800, 2400, 'G+1', 'Premium', 'completed', 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80', 2026, 1, 1),
('Luxury Stilt + 3 Floor Villa', 'Boopesh', 'Anna Nagar', 'Pattukkottai', 2200, 3100, 'G+3', 'Luxury', 'completed', 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=800&q=80', 2026, 1, 2),
('Modern G+2 Architectural Villa', 'Rahul', 'Bus Stand Road', 'Pattukkottai', 2000, 2750, 'G+2', 'Premium', 'completed', 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=800&q=80', 2026, 1, 3),
('Executive G+2 Family Home', 'Rajadurai', 'Thanjavur Road', 'Pattukkottai', 2000, 2750, 'G+2', 'Premium', 'completed', 'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=800&q=80', 2026, 1, 4),
('Elegant G+2 Independent House', 'Vignesh', 'Railway Station Road', 'Pattukkottai', 2000, 2750, 'G+2', 'Standard', 'completed', 'https://images.unsplash.com/photo-1600573472550-8090b5e0745e?auto=format&fit=crop&w=800&q=80', 2026, 1, 5),
('Spacious G+2 Residential Project', 'KVT Family', 'Aranthangi Road', 'Pattukkottai', 2000, 2750, 'G+2', 'Premium', 'completed', 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=800&q=80', 2026, 1, 6)
ON DUPLICATE KEY UPDATE `title` = VALUES(`title`);

SET FOREIGN_KEY_CHECKS = 1;
